repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.2.3'
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma
    -   id: check-vcs-permalinks
    -   id: no-commit-to-branch
        args: [--branch, master, --pattern, release.*]
    -   id: detect-private-key
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent=2, --no-sort-keys, --no-ensure-ascii]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: flake8
        types: [python]
        args: [--max-complexity=12, --max-line-length=120]
    -   id: mixed-line-ending
        types: [python]
        args: [--fix=lf]
